### ISSUE TITLE
2.4版本插件在更新1.4软件中心后提示“进程未运行”

### ISSUE THREAD

**Issue by nyanmisaka** [koolshare/merlin-aria2#10]
设备是 AC68U，7.9 固件，今天更新1.4软件中心后发现 aria2 连不上了，提示“进程未运行”，尝试重启插件无果，重启路由器无果，手动输入论坛中的一些命令也无法解决，重装插件也不行。

其实这个问题在1.3软件中心的时候也发生过，只能重置路由器解决，就连格掉 jffs 也不能解决，每次出问题都来一遍很花时间。猜测可能是插件起了什么冲突，因为手动执行 aria2_run.sh 的时候都会直接弹出报错信息`/koolshare/aria2/aria2_run.sh: eval: line 1: syntax error: unexpected "("`，并且2.4插件无法在软件中心手动安装，会报错失败。

经测试回退2.3版本正常使用。

还请作者大大帮忙解决一下，十分感谢！

**Comment by sadoneli** [comment]
和1.4的软件中心没多大关系，但是和软件中心确实又有关系，因为软件中心数据库skipd的问题，导致shell拿到的数据出了错误，skipd是自带在固件的，不跟随软件中心更新包的
1. 更新了一个版本，但是可能不会完全解决（弱解决方案）
2. 要强解决方案的话，一些插件内的值，需要用base64加密储存，才能避免问题（待观察）
3. 最终解决的话可能需要依赖固件内的skipd程序更新才能搞定

**Comment by nyanmisaka** [comment]
感谢解读 :-)
