### ISSUE TITLE
在插件页面修改个别配置，aria2.conf没有相应变动

### ISSUE THREAD

**Issue by nyanmisaka** [koolshare/merlin-aria2#11]
比如BT设置中的端口号、Tracker，下载限制中的最大同时下载任务数等等（还有一些，未逐个测试），在chrome端填入，点击提交，查看 aria2.conf 中没有变化，网页前端获取的配置也是未经修改过的初始值。这个问题在近两个版本2.3和2.4都存在，之前的忘记了，现在手动配置conf后正常。

**Comment by sadoneli** [comment]
#10 
另外是否能帖子会导致问题的一些配置的具体值，比如Tracker等

**Comment by AriaLyy** [comment]
+1，现在还有这个问题
