### ISSUE TITLE
Bt 下载没速度，能否帮忙解决下。

### ISSUE THREAD

**Issue by anny29** [koolshare/merlin-aria2#5]

**Comment by NemoAlex** [comment]
aria2 是一个标准的 BT 客户端。
在目前中国的网络环境下，标准的 BT 客户端没有速度是正常现象。
请通过搜索引擎来进一步了解详细情况。
不属于本项目的讨论范畴。

**Comment by anny29** [comment]
好吧，感谢回复。相同环境下使用download master对同一个bt种子可以正常下载。我再看看aria2的log吧，之前log中只有bt tracker连接失败的信息。
